

-- FAQ
CREATE TABLE FAQ (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    question TEXT,
    answer TEXT,
    createDate DATE
);

INSERT INTO FAQ (question, answer, createDate) values('What is Next.js?', 'Next.js is a minimialist React framework designed to allow applications to scale easily over their lifespan. Next.js gives you the best developer experience with all the features you need for production: hybrid static & server rendering, TypeScript support, smart bundling, route pre-fetching, and more. No config needed.', DATE('2019-11-01'));
INSERT INTO FAQ (question, answer, createDate) values('What is React?', 'React is an open-source, front end, JavaScript library for building user interfaces or UI components. It is maintained by Facebook and a community of individual developers and companies. React can be used as a base in the development of single-page or mobile applications', DATE('2020-11-01'));
INSERT INTO FAQ (question, answer, createDate) values('What is Nivo?', 'Nivo provides supercharged React components to easily build dataviz apps, built on top of d3. Several libraries already exist for React d3 integration, but just a few provide server side rendering ability and fully declarative charts.', DATE('2018-11-01'));
INSERT INTO FAQ (question, answer, createDate) values('What is SWR?', 'SWR is a React Hooks library for remote data fetching. The name “SWR” is derived from stale-while-revalidate, a cache invalidation strategy popularized by HTTP RFC 5861. SWR first returns the data from cache (stale), then sends the fetch request (revalidate), and finally comes with the up-to-date data again. With SWR, components will get a stream of data updates constantly and automatically. Thus, the UI will be always fast and reactive.', DATE('2018-11-01'));
INSERT INTO FAQ (question, answer, createDate) values('What is Material UI?', 'Material Design is a design language developed by Google in 2014. Expanding on the "card" motifs that debuted in Google Now, Material Design uses more grid-based layouts, responsive animations and transitions, padding, and depth effects such as lighting and shadows.', DATE('2018-11-01'));
INSERT INTO FAQ (question, answer, createDate) values('What is Formik?', "Formik is the world's most popular open source form library for React and React Native.", DATE('2018-11-01'));

-- User
CREATE TABLE User (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    taxID TEXT,
    merchantName TEXT,
    dba TEXT,
    externalMID TEXT,
    address1 TEXT, 
    address2 TEXT,
    city TEXT,
    region TEXT, 
    country TEXT,
    postalCode TEXT,
    tenure TEXT, 
    createDate DATE,
    logoUrl TEXT,
    logoWidth INTEGER,
    logoHeight INTEGER
);

INSERT INTO User (taxID, merchantName, dba, externalMID, address1, address2, city, region, country, postalCode, tenure, createDate, logoUrl, logoWidth, logoHeight) values('123456789', 'Barbara S. Jones', 'Coca-Cola Company', '123456789123', '123 Peachtree St NW', 'APT 101', 'Atlanta', 'Georgia', 'United States', '12345', '1 year', DATE('2021-03-01'), '/photos/logos/Coca-Cola_logo.svg', 1059, 347);
INSERT INTO User (taxID, merchantName,  dba, externalMID, address1, address2, city, region, country, postalCode, tenure, createDate, logoUrl, logoWidth, logoHeight) values('123456780', 'William Heath', 'Pepsi', '123456789124', '123 Main St', 'APT 202', 'New York City', 'New York', 'United States',  '12345', '2 years', DATE('2021-03-02'), '/photos/logos/Pepsi_logo_new.svg', 496, 158);
INSERT INTO User (taxID, merchantName, dba, externalMID, address1, address2, city, region, country, postalCode, tenure, createDate, logoUrl, logoWidth, logoHeight) values('123456781', 'Finley Matthews','Delta', '123456789125', '123 Englewood St', 'APT 101', 'Chicago', 'Illinois', 'United States', '12345', '1 year 6 mo', DATE('2021-03-03'), '/photos/logos/Delta_logo.svg', 1000, 154);
INSERT INTO User (taxID, merchantName, dba, externalMID, address1, address2, city, region, country, postalCode, tenure, createDate, logoUrl, logoWidth, logoHeight) values('123456782', 'Kaled Aguilera Villegas', 'Marriot', '123456789126', '123 Castle Heights Ave', '', 'Los Angeles', 'California', 'United States',  '90034', '4 year', DATE('2021-03-04'), '/photos/logos/Marriott_Logo.svg', 744, 384);
INSERT INTO User (taxID, merchantName,  dba, externalMID, address1, address2, city, region, country, postalCode, tenure, createDate, logoUrl, logoWidth, logoHeight) values('123456783', 'Navila Escobedo Luna','Hilton', '123456789127', '123 Broad St', 'APT 101', 'Seattle', 'Washington', 'United States', '12345', '4 year 6 mo', DATE('2021-03-05'), '/photos/logos/Hilton-Hotels_Logo.svg', 362, 276);
INSERT INTO User (taxID, merchantName,  dba, externalMID, address1, address2, city, region, country, postalCode, tenure, createDate, logoUrl, logoWidth, logoHeight) values('123456784', 'Phillipp Richter','Foot Locker', '123456789128', '123 W Peachtree Rd NW', 'APT 303', 'Atlanta', 'Georgia', 'United States', '12345', '4 year 6 mo', DATE('2021-03-05'), '/photos/logos/Foot_Locker_logo.svg', 340, 206);


-- CAR
CREATE TABLE Car (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    make TEXT,
    model TEXT,
    year INTEGER,
    fuelType TEXT,
    kilometers INTEGER,
    details TEXT,
    price INTEGER,
    photoUrl TEXT
);

INSERT INTO Car (make, model, year, kilometers, fuelType, price, photoUrl, details) values('Audi', 'A2', 2003 ,123456, 'Petrol' ,8199, '/photos/cars/audi-a2-2003-8199.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
INSERT INTO Car (make, model, year, kilometers, fuelType, price, photoUrl, details) values('BMW', '116', 2013 ,1231231, 'Petrol' ,12999, '/photos/cars/bmw-116-d-line-urban-2013.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
INSERT INTO Car (make, model, year, kilometers, fuelType, price, photoUrl, details) values('BMW', '320', 2009 ,655656, 'Petrol' ,18999, '/photos/cars/bmw-320-2009-18000.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
INSERT INTO Car (make, model, year, kilometers, fuelType, price, photoUrl, details) values('BMW', 'x1', 2012 ,565656, 'Diesel' ,24000, '/photos/cars/bmw-x1-2012-24999.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
INSERT INTO Car (make, model, year, kilometers, fuelType, price, photoUrl, details) values('Ford', 'Fiesta', 2008 ,433444, 'Petrol' ,5590, '/photos/cars/ford-fiesta-2008-5950.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
INSERT INTO Car (make, model, year, kilometers, fuelType, price, photoUrl, details) values('Ford', 'Fiesta', 2014 ,343434, 'Petrol' ,9950, '/photos/cars/ford-fiesta-2014-9950.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
INSERT INTO Car (make, model, year, kilometers, fuelType, price, photoUrl, details) values('Mazda', '6', 2015 ,343411, 'Petrol' ,21000, '/photos/cars/mazda-6-2015.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
INSERT INTO Car (make, model, year, kilometers, fuelType, price, photoUrl, details) values('Merces-Benz', '200', 2015 ,111111, 'Petrol' ,24999, '/photos/cars/mercedes-benz-200-2015-24999.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
INSERT INTO Car (make, model, year, kilometers, fuelType, price, photoUrl, details) values('Merces-Benz', 'e250', 2011 ,123443, 'Diesel' ,29800, '/photos/cars/mercedes-benz-e250-2011-29800.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
INSERT INTO Car (make, model, year, kilometers, fuelType, price, photoUrl, details) values('Peugeot', '3008', 2014 ,77000, 'Petrol' ,18999, '/photos/cars/peugeot-3008-2014-17999.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
INSERT INTO Car (make, model, year, kilometers, fuelType, price, photoUrl, details) values('Renault', 'Clio', 2017 ,123133, 'Diesel' ,13485, '/photos/cars/renault-clio-2017-13485.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
INSERT INTO Car (make, model, year, kilometers, fuelType, price, photoUrl, details) values('Renault', 'Espace', 2004 ,123123, 'Petrol' ,9800, '/photos/cars/renault-espace-2004.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
INSERT INTO Car (make, model, year, kilometers, fuelType, price, photoUrl, details) values('Renault', 'Megane IV', 2016 ,123123, 'Diesel' ,15890, '/photos/cars/renault-megane-2016-15890.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
INSERT INTO Car (make, model, year, kilometers, fuelType, price, photoUrl, details) values('Seat', 'Leon', 2010 ,44444, 'Diesel' ,13650, '/photos/cars/seat-leon-2010-13650.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
INSERT INTO Car (make, model, year, kilometers, fuelType, price, photoUrl, details) values('Smart', 'for two', 2008 ,5534, 'Diesel' ,5800, '/photos/cars/smart-fortwo-2008-5800.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
INSERT INTO Car (make, model, year, kilometers, fuelType, price, photoUrl, details) values('Smart', 'for two', 2012 ,43434, 'Diesel' ,7950, '/photos/cars/smart-fortwo-2012-7950.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
INSERT INTO Car (make, model, year, kilometers, fuelType, price, photoUrl, details) values('Smart', 'for two', 2003 ,343434, 'Diesel' ,8850, '/photos/cars/smart-fortwo-passion-2003-8888.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
INSERT INTO Car (make, model, year, kilometers, fuelType, price, photoUrl, details) values('Smart', 'for two', 2015 ,343434, 'Diesel' ,11500, '/photos/cars/smart-fortwo-passion-2015-11500.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
INSERT INTO Car (make, model, year, kilometers, fuelType, price, photoUrl, details) values('Volkswagen', 'EOS', 2008 ,343434, 'Diesel' ,14700, '/photos/cars/volkswagen-eos-2008-14700.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
INSERT INTO Car (make, model, year, kilometers, fuelType, price, photoUrl, details) values('Volkswagen', 'Golf', 2013 ,123123, 'Diesel' ,18300, '/photos/cars/volkswagen-golf-2013-18300.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
INSERT INTO Car (make, model, year, kilometers, fuelType, price, photoUrl, details) values('Volkswagen', 'Tiguan', 2007 ,1231234, 'Petrol' ,14299, '/photos/cars/volkswagen-tiguan-2007-14299.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');

-- Down
DROP TABLE Car;
DROP TABLE FAQ;
DROP TABLE User;